apiVersion: v1
kind: Service
metadata:
  name: k8s-test-app-srv
spec:
  type: LoadBalancer
  selector:
    app: test-app 
    tier: backend
  ports:  
    port: 80
    targetPort: 8080
    # port: 443
    # targetPort: 443
---
apiVersion: apps/v1x
kind: Deployment
metadata:
  name: k8s-test-app-depl
spec:
  replicas: 3
  selector: # must be mapping with labels of pod(monitoring and management pods)
    matchLabels:
      app: test-app 
      tier: backend
  template:
    apiVersion: v1
    metadata:
      labels:
        app: test-app
        tier: backend
    spec:
      container:
        - name: test-app-container 
          image: mountainseadevops/k8s-first-app
          imagePullPolicy: Always
          livenessProbe: 
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySecond: 5

